version: '3'

services:
  tuubaa-bot:
    build: .
    container_name: tuubaa-twitch-bot
    restart: unless-stopped
    volumes:
      - ./tokens.json:/app/tokens.json
      - ./.env:/app/.env
    environment:
      - NODE_ENV=production

    healthcheck:
      test: ["CMD", "node", "-e", "require('tmi.js')"]
      interval: 60s
      timeout: 10s
      retries: 3