FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY tsconfig.json ./
COPY src/ ./src/

RUN npm run build

COPY .env.template .env

RUN if [ ! -f tokens.json ]; then echo "{}" > tokens.json; fi

VOLUME ["/app/tokens.json", "/app/.env"]

EXPOSE ${PORT:-4000}

CMD ["npm","run", "start"]